name: jes
mf: false
run_function:
  _target_: mf_prior_experiments.run.run_botorch
searcher:
  # _partial_: true  # To not instantiate the class directly as required by neps
  _target_: botorch.acquisition.joint_entropy_search.qLowerBoundJointEntropySearch
