name: mf-mes
mf: true
run_function:
  _target_: mf_prior_experiments.run.run_botorch
searcher:
  # _partial_: true  # To not instantiate the class directly as required by neps
  _target_: botorch.acquisition.max_value_entropy_search.qMultiFidelityMaxValueEntropy
