name: ours_v1_3
mf: true
run_function:
  _target_: mf_prior_experiments.run.run_neps
searcher:
  _partial_: true  # To not instantiate the class directly as required by neps
  _target_: neps.optimizers.multi_fidelity_prior.v1.OurOptimizerV1_3
