defaults:
  - benchmark: random_search
  - algorithm: jahs_cifar10
  - override hydra/job_logging: full
  - _self_

experiment_group: test_${now:%Y-%m-%d-%H-%M-%S}
experiment_name: algorithm=${algorithm.name}/benchmark=${benchmark.name}/seed=${seed}
seed: 2

hydra:
  run:
    dir: results/${experiment_group}/${experiment_name}
  job:
    chdir: true
