defaults:
  - benchmark: jahs_cifar10
  - override hydra/job_logging: full
  - _self_
run_function:
  _target_: mf_prior_experiments.generate_priors.run_for_priors
nsamples: 25
save_dir: results_for_priors/
seed: 9999  # different seed from what random search or other optimizers will generally see
#hydra:
#  run:
#    dir: results_for_priors/hydra_logs
#  job:
#    chdir: true
