name: jahs_fashion_mnist_prior-bad
api:
  name: jahs_fashion_mnist
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -10.295780181884766
prior_lowest_error: -22.40579605102539
best_10_error: -93.884033203125
best_25_error: -93.884033203125
best_100_error: -94.00015258789062
