name: jahs_fashion_mnist_prior-bad
api:
  name: jahs_fashion_mnist
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 7.388114929199219
prior_lowest_error: 7.3319244384765625
best_10_error: 5.115966796875
best_25_error: 5.115966796875
best_100_error: 4.999847412109375
