name: jahs_cifar10_prior-bad
api:
  name: jahs_cifar10
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -65.87297058105469
prior_lowest_error: -65.87297058105469
best_10_error: -88.48519134521484
best_25_error: -89.80328369140625
best_100_error: -89.82088470458984
