name: jahs_colorectal_histology_prior-good
api:
  name: jahs_colorectal_histology
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 7.398216247558594
prior_lowest_error: 7.394645690917969
best_10_error: 6.7841949462890625
best_25_error: 6.07537841796875
best_100_error: 5.4381866455078125
