name: jahs_colorectal_histology_prior-good
api:
  name: jahs_colorectal_histology
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 6.558380126953125
prior_lowest_error: 6.5574493408203125
best_10_error: 5.36956787109375
best_25_error: 5.2310333251953125
best_100_error: 4.924247741699219
