name: jahs_fashion_mnist_prior-medium
api:
  name: jahs_fashion_mnist
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -92.58428955078125
prior_lowest_error: -93.51701354980469
best_10_error: -93.884033203125
best_25_error: -93.884033203125
best_100_error: -94.00015258789062
