name: jahs_cifar10_prior-good
api:
  name: jahs_cifar10
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -88.92434692382812
prior_lowest_error: -88.98591613769531
best_10_error: -88.48519134521484
best_25_error: -89.80328369140625
best_100_error: -89.82088470458984
