name: jahs_colorectal_histology_prior-really_good
api:
  name: jahs_colorectal_histology
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: really_good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 6.07537841796875
prior_lowest_error: 6.070396423339844
best_10_error: 6.7841949462890625
best_25_error: 6.07537841796875
best_100_error: 5.4381866455078125
