name: jahs_cifar10_prior-really_bad
api:
  name: jahs_cifar10
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: really_bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 34.18463897705078
prior_lowest_error: 34.18463897705078
best_10_error: 10.514808654785156
best_25_error: 9.19671630859375
best_100_error: 9.179115295410156
