name: jahs_cifar10_prior-medium
api:
  name: jahs_cifar10
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -85.4049301147461
prior_lowest_error: -85.68867492675781
