name: jahs_fashion_mnist_prior-good
api:
  name: jahs_fashion_mnist
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 5.5821380615234375
prior_lowest_error: 5.395599365234375
best_10_error: 5.281394958496094
best_25_error: 5.281394958496094
best_100_error: 4.940925598144531
