name: jahs_colorectal_histology_prior-medium
api:
  name: jahs_colorectal_histology
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -89.5498275756836
prior_lowest_error: -89.55579376220703
best_10_error: -92.21580505371094
best_25_error: -92.92462158203125
best_100_error: -93.56181335449219
