name: jahs_fashion_mnist_prior-bad
api:
  name: jahs_fashion_mnist
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 19.645431518554688
prior_lowest_error: 17.337142944335938
best_10_error: 5.115966796875
best_25_error: 5.115966796875
best_100_error: 4.999847412109375
