name: jahs_cifar10_prior-bad
api:
  name: jahs_cifar10
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  default_score: -10.711856842041016
