name: jahs_fashion_mnist_prior-bad
api:
  name: jahs_fashion_mnist
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 11.426750183105469
prior_lowest_error: 5.986946105957031
best_10_error: 5.281394958496094
best_25_error: 5.281394958496094
best_100_error: 4.940925598144531
