name: jahs_colorectal_histology_prior-bad
api:
  name: jahs_colorectal_histology
  datadir: ${hydra:runtime.cwd}/data/jahs-bench-data
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
