name: lcbench-189866_prior-medium
api:
  name: lcbench
  prior: medium
  datadir: ${hydra:runtime.cwd}/data/yahpo-gym-data
  task_id: '189866'
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
