name: lcbench-189862_prior-medium
api:
  name: lcbench
  prior: medium
  datadir: ${hydra:runtime.cwd}/data/yahpo-gym-data
  task_id: '189862'
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.23311984539031982
prior_lowest_error: 0.23311984539031982
