name: lcbench-189866_prior-bad
api:
  name: lcbench
  prior: bad
  datadir: ${hydra:runtime.cwd}/data/yahpo-gym-data
  task_id: '189866'
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.5191668570041656
prior_lowest_error: 0.48823487758636475
