name: lm1b_transformer_2048_prior-bad
api:
  name: lm1b_transformer_2048
  prior: bad
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.8066880702972412
prior_lowest_error: 0.797473669052124
