name: lm1b_transformer_2048_prior-medium
api:
  name: lm1b_transformer_2048
  prior: medium
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.7121967673301697
prior_lowest_error: 0.7121967673301697
