name: mfh3_moderate_prior-perfect-noisy0.125
api:
  name: mfh3_moderate
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -2.606189255143274
prior_lowest_error: -2.606189255143274
optimum: -3.8627797869493365
