name: mfh3_bad_prior-perfect-noisy0.125
api:
  name: mfh3_bad
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -1.992760837185196
prior_lowest_error: -1.992760837185196
optimum: -3.8627797869493365
