name: mfh3_bad_prior-medium
api:
  name: mfh3_bad
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -0.46183250978520557
prior_lowest_error: -0.46183250978520557
optimum: -3.8627797869493365
