name: mfh3_good_prior-good-noisy0.125
api:
  name: mfh3_good
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.8824039140367039
prior_lowest_error: -0.8824039140367039
optimum: -3.8627797869493365
