name: mfh3_moderate_prior-bad
api:
  name: mfh3_moderate
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -0.0007863029536155626
prior_lowest_error: -0.0007863029536155626
optimum: -3.8627797869493365
