name: mfh3_moderate_prior-medium-noisy0.125
api:
  name: mfh3_moderate
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.4348299875296486
prior_lowest_error: -0.4348299875296486
optimum: -3.8627797869493365
