name: mfh3_moderate_prior-good-noisy0.125
api:
  name: mfh3_moderate
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -3.0414289076095455
prior_lowest_error: -3.0414289076095455
optimum: -3.8627797869493365
