name: mfh3_terrible_prior-perfect-noisy0.125
api:
  name: mfh3_terrible
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -2.0022115493048718
prior_lowest_error: -2.0022115493048718
optimum: -3.8627797869493365
