name: mfh3_bad_prior-perfect-noisy0.125
api:
  name: mfh3_bad
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -3.2603450353993844
prior_lowest_error: -3.2603450353993844
optimum: -3.8627797869493365
