name: mfh3_bad_prior-good-noisy0.125
api:
  name: mfh3_bad
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -1.4124548364023504
prior_lowest_error: -1.4124548364023504
optimum: -3.8627797869493365
