name: mfh3_terrible_prior-good-noisy0.125
api:
  name: mfh3_terrible
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
default_score: -3.86278
