name: mfh3_good_prior-good-noisy0.125
api:
  name: mfh3_good
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -2.7382910007308303
prior_lowest_error: -2.7382910007308303
optimum: -3.8627797869493365
