name: mfh3_terrible_prior-good-noisy0.125
api:
  name: mfh3_terrible
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -2.3823372367339077
prior_lowest_error: -2.3823372367339077
optimum: -3.8627797869493365
