name: mfh3_terrible_prior-medium-noisy0.125
api:
  name: mfh3_terrible
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -0.793295250441366
prior_lowest_error: -0.793295250441366
optimum: -3.8627797869493365
