name: mfh3_moderate_prior-bad-noisy0.125
api:
  name: mfh3_moderate
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -0.00479313460315263
prior_lowest_error: -0.00479313460315263
optimum: -3.8627797869493365
