name: mfh3_good_prior-medium-noisy0.125
api:
  name: mfh3_good
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -0.27248206087495064
prior_lowest_error: -0.27248206087495064
optimum: -3.8627797869493365
