name: mfh3_good_prior-perfect-noisy0.125
api:
  name: mfh3_good
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
default_score: -3.86278
