name: mfh3_moderate_prior-good
api:
  name: mfh3_moderate
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -3.042213459819952
prior_lowest_error: -3.042213459819952
optimum: -3.8627797869493365
