name: mfh3_terrible_prior-bad-noisy0.125
api:
  name: mfh3_terrible
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.013388585755979824
prior_lowest_error: -0.013388585755979824
optimum: -3.8627797869493365
