name: mfh3_terrible_prior-perfect-noisy0.125
api:
  name: mfh3_terrible
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -3.3734059148777007
prior_lowest_error: -3.3734059148777007
optimum: -3.8627797869493365
