name: mfh3_terrible_prior-perfect
api:
  name: mfh3_terrible
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -3.8627797869493365
prior_lowest_error: -3.8627797869493365
optimum: -3.8627797869493365
