name: mfh6_bad_prior-good-noisy0.125
api:
  name: mfh6_bad
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -0.17809386443829675
prior_lowest_error: -0.17809386443829675
optimum: -3.322368011391339
