name: mfh6_moderate_prior-good-noisy0.125
api:
  name: mfh6_moderate
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -2.004934898265836
prior_lowest_error: -2.004934898265836
optimum: -3.322368011391339
