name: mfh6_good_prior-good-noisy0.125
api:
  name: mfh6_good
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.20751689806014634
prior_lowest_error: -0.20751689806014634
optimum: -3.322368011391339
