name: mfh6_moderate_prior-perfect-noisy0.125
api:
  name: mfh6_moderate
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -2.592846256953257
prior_lowest_error: -2.592846256953257
optimum: -3.322368011391339
