name: mfh6_terrible_prior-bad
api:
  name: mfh6_terrible
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -0.0008124431073983237
prior_lowest_error: -0.0008124431073983237
optimum: -3.322368011391339
