name: mfh6_good_prior-medium-noisy0.125
api:
  name: mfh6_good
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -0.0569010908496416
prior_lowest_error: -0.0569010908496416
optimum: -3.322368011391339
