name: mfh6_good_prior-medium
api:
  name: mfh6_good
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -0.06430042239802497
prior_lowest_error: -0.06430042239802497
optimum: -3.322368011391339
