name: mfh6_bad_prior-perfect-noisy0.125
api:
  name: mfh6_bad
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -1.3547097769640593
prior_lowest_error: -1.3547097769640593
optimum: -3.322368011391339
