name: mfh6_bad_prior-perfect-noisy0.125
api:
  name: mfh6_bad
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -2.3591526647496344
prior_lowest_error: -2.3591526647496344
optimum: -3.322368011391339
