name: mfh6_terrible_prior-perfect
api:
  name: mfh6_terrible
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -3.322368011391339
prior_lowest_error: -3.322368011391339
optimum: -3.322368011391339
