name: mfh6_terrible_prior-good-noisy0.125
api:
  name: mfh6_terrible
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.11727092959449027
prior_lowest_error: -0.11727092959449027
optimum: -3.322368011391339
