name: mfh6_terrible_prior-bad-noisy0.125
api:
  name: mfh6_terrible
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -8.158952758614904e-05
prior_lowest_error: -8.158952758614904e-05
optimum: -3.322368011391339
