name: mfh6_good_prior-perfect-noisy0.125
api:
  name: mfh6_good
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -2.6900115087404983
prior_lowest_error: -2.6900115087404983
optimum: -3.322368011391339
