name: mfh6_moderate_prior-bad-noisy0.125
api:
  name: mfh6_moderate
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.00045379641525238523
prior_lowest_error: -0.00045379641525238523
optimum: -3.322368011391339
