name: mfh6_bad_prior-medium-noisy0.125
api:
  name: mfh6_bad
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.01760095018531786
prior_lowest_error: -0.01760095018531786
optimum: -3.322368011391339
