name: mfh6_bad_prior-good
api:
  name: mfh6_bad
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: -0.7982512344535452
prior_lowest_error: -0.7982512344535452
optimum: -3.322368011391339
