name: mfh6_terrible_prior-bad-noisy0.125
api:
  name: mfh6_terrible
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.006422599665835734
prior_lowest_error: -0.006422599665835734
optimum: -3.322368011391339
