name: mfh6_terrible_prior-medium-noisy0.125
api:
  name: mfh6_terrible
  prior: medium
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -0.1493642416744621
prior_lowest_error: -0.1493642416744621
optimum: -3.322368011391339
