name: mfh6_good_prior-bad-noisy0.125
api:
  name: mfh6_good
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.00782776614764565
prior_lowest_error: -0.00782776614764565
optimum: -3.322368011391339
