name: mfh6_terrible_prior-good-noisy0.125
api:
  name: mfh6_terrible
  prior: good
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.125
prior_highest_fidelity_error: -1.438512284471566
prior_lowest_error: -1.438512284471566
optimum: -3.322368011391339
