name: mfh6_bad_prior-bad-noisy0.125
api:
  name: mfh6_bad
  prior: bad
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -0.0002928267965753371
prior_lowest_error: -0.0002928267965753371
optimum: -3.322368011391339
