name: mfh6_terrible_prior-perfect-noisy0.125
api:
  name: mfh6_terrible
  prior: perfect
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
  noisy_prior: true
  prior_noise_scale: 0.25
prior_highest_fidelity_error: -1.4140910401130102
prior_lowest_error: -1.4140910401130102
optimum: -3.322368011391339
