name: translatewmt_xformer_64_prior-bad
api:
  name: translatewmt_xformer_64
  prior: bad
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.7291821837425232
prior_lowest_error: 0.7283704876899719
