name: translatewmt_xformer_64_prior-really_good
api:
  name: translatewmt_xformer_64
  prior: really_good
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.36273840069770813
prior_lowest_error: 0.36273840069770813
best_10_error: 0.39859017729759216
best_25_error: 0.3551706075668335
best_100_error: 0.3421264886856079
