name: translatewmt_xformer_64_prior-good
api:
  name: translatewmt_xformer_64
  prior: good
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.3588021397590637
prior_lowest_error: 0.3588021397590637
