name: translatewmt_xformer_64_prior-really_bad
api:
  name: translatewmt_xformer_64
  prior: really_bad
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.6724655032157898
prior_lowest_error: 0.6724655032157898
best_10_error: 0.39859017729759216
best_25_error: 0.3551706075668335
best_100_error: 0.3421264886856079
