name: uniref50_transformer_128_prior-good
api:
  name: uniref50_transformer_128
  prior: good
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.8078969120979309
prior_lowest_error: 0.8078969120979309
