name: uniref50_transformer_128_prior-medium
api:
  name: uniref50_transformer_128
  prior: medium
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.8177037835121155
prior_lowest_error: 0.8177037835121155
