name: uniref50_transformer_128_prior-bad
api:
  name: uniref50_transformer_128
  prior: bad
  datadir: ${hydra:runtime.cwd}/data/pd1-data
  _target_: mfpbench.get
  seed: ${seed}
  preload: true
prior_highest_fidelity_error: 0.858542799949646
prior_lowest_error: 0.858542799949646
